figma.showUI(__html__, { width: 368, height: 350 });

type NodeType = "none" | "process" | "start-end" | "yes-no";
type ConnectorSide = "LEFT" | "RIGHT" | "TOP" | "BOTTOM";
type ConnectorPreference = { sourceSide: ConnectorSide; targetSide: ConnectorSide };
type PluginRequest =
  | { type: "generate-connector" }
  | { type: "set-debug"; payload: { enabled: boolean } }
  | { type: "set-connector-sides"; payload: ConnectorPreference }
  | { type: "set-node-type"; payload: { nodeType: NodeType } };
type FrameLikeNode = SceneNode & DimensionAndPositionMixin;
type NodeBounds = { x: number; y: number; width: number; height: number };

let previousFrameSelection = new Set<string>();
let frameSelectionOrder: string[] = [];
let isSyncingFallbackLinks = false;
let pendingSyncTimer: ReturnType<typeof setTimeout> | null = null;
let fallbackPollingTimer: ReturnType<typeof setInterval> | null = null;
let debugEnabled = false;
let isAutoGeneratingConnector = false;
let lastAutoGeneratedPairKey: string | null = null;
let isAutoInsertingNode = false;
let isDocumentSyncReady = false;
let connectorPreference: ConnectorPreference = { sourceSide: "RIGHT", targetSide: "LEFT" };

const FALLBACK_LINK_MARK = "flow-builder-fallback-link";
const FALLBACK_LINK_START_ID = "flow-builder-fallback-start-id";
const FALLBACK_LINK_END_ID = "flow-builder-fallback-end-id";
const FALLBACK_ROLE_KEY = "flow-builder-fallback-role";
const FALLBACK_CONTAINER_ROLE = "flow-builder-container";
const FALLBACK_DEBUG_ENABLED = "flow-builder-debug-enabled";
const FALLBACK_CONNECTOR_PREFS = "flow-builder-connector-preferences";
const FALLBACK_LINK_SOURCE_SIDE = "flow-builder-link-source-side";
const FALLBACK_LINK_TARGET_SIDE = "flow-builder-link-target-side";
const FLOW_NODE_MARK = "flow-builder-node";
const FLOW_NODE_LABEL_ROLE = "flow-builder-node-label";
const FLOW_NODE_PROCESS_SHAPE_ROLE = "flow-builder-process-shape";
const SYNC_THROTTLE_MS = 33;
const GEOMETRY_EPSILON = 0.25;
const POLLING_SYNC_MS = 250;
const FONT_REGULAR: FontName = { family: "Inter", style: "Regular" };

figma.ui.onmessage = async (msg: PluginRequest) => {
  try {
    if (msg.type === "generate-connector") {
      await generateConnectorFromSelection();
      sendStatus("success", "Successful");
      return;
    }
    if (msg.type === "set-debug") {
      debugEnabled = msg.payload.enabled;
      await figma.clientStorage.setAsync(FALLBACK_DEBUG_ENABLED, debugEnabled);
      applyDebugVisibilityToAllLinks();
      emitDebugState();
      sendStatus("success", debugEnabled ? "Debug ON" : "Debug OFF");
      return;
    }
    if (msg.type === "set-connector-sides") {
      connectorPreference = {
        sourceSide: msg.payload.sourceSide,
        targetSide: msg.payload.targetSide
      };
      await figma.clientStorage.setAsync(FALLBACK_CONNECTOR_PREFS, connectorPreference);
      emitConnectorPreferenceState();
      sendStatus("success", "Connector sides updated");
      return;
    }
    if (msg.type === "set-node-type") {
      await applyNodeTypeToSelection(msg.payload.nodeType);
      sendStatus("success", "Node updated");
      return;
    }
    throw new Error("Unsupported command.");
  } catch (error) {
    const message = error instanceof Error ? error.message : "Unexpected plugin error.";
    figma.notify(message, { error: true });
    sendStatus("error", message);
  }
};

figma.on("selectionchange", () => {
  updateSelectionOrder();
  emitConnectorSelectionState();
  emitNodeTypeState();
  void maybeAutoGenerateConnector();
  void maybeAutoInsertNodeFromConnector();
});

void initializeSettings();
void initializeDocumentSync();

async function initializeSettings(): Promise<void> {
  try {
    const storedDebug = await figma.clientStorage.getAsync(FALLBACK_DEBUG_ENABLED);
    debugEnabled = storedDebug === true;
    const storedConnectorPrefs = await figma.clientStorage.getAsync(FALLBACK_CONNECTOR_PREFS);
    if (
      storedConnectorPrefs &&
      typeof storedConnectorPrefs === "object" &&
      isConnectorSide((storedConnectorPrefs as { sourceSide?: unknown }).sourceSide) &&
      isConnectorSide((storedConnectorPrefs as { targetSide?: unknown }).targetSide)
    ) {
      connectorPreference = {
        sourceSide: (storedConnectorPrefs as { sourceSide: ConnectorSide }).sourceSide,
        targetSide: (storedConnectorPrefs as { targetSide: ConnectorSide }).targetSide
      };
    }
    emitDebugState();
    emitConnectorPreferenceState();
    emitConnectorSelectionState();
    emitNodeTypeState();
    setTimeout(() => emitDebugState(), 300);
    setTimeout(() => emitConnectorPreferenceState(), 300);
    setTimeout(() => emitConnectorSelectionState(), 300);
    setTimeout(() => emitNodeTypeState(), 300);
  } catch {
    debugEnabled = false;
  }
}

function emitDebugState(): void {
  figma.ui.postMessage({ type: "debug-state", payload: { enabled: debugEnabled } });
}

function emitConnectorPreferenceState(): void {
  figma.ui.postMessage({ type: "connector-side-state", payload: connectorPreference });
}

function emitConnectorSelectionState(): void {
  const selectableIds = new Set(figma.currentPage.selection.filter((node) => isFrameOrImage(node)).map((node) => node.id));
  const orderedSelectableIds = frameSelectionOrder.filter((id) => selectableIds.has(id));
  figma.ui.postMessage({
    type: "connector-selection-state",
    payload: {
      sourceSelected: orderedSelectableIds.length >= 1,
      targetSelected: orderedSelectableIds.length >= 2
    }
  });
}

function emitNodeTypeState(): void {
  const selected = figma.currentPage.selection;
  if (selected.length === 1) {
    const node = selected[0];
    if (node.type === "FRAME" && node.getPluginData(FLOW_NODE_MARK) === "true") {
      const currentNodeTypeRaw = node.getPluginData("flow-builder-node-type");
      const currentNodeType = isNodeType(currentNodeTypeRaw) ? currentNodeTypeRaw : null;
      figma.ui.postMessage({
        type: "node-type-state",
        payload: { enabled: true, selectedType: currentNodeType }
      });
      return;
    }
  }
  figma.ui.postMessage({
    type: "node-type-state",
    payload: { enabled: false, selectedType: null }
  });
}

async function initializeDocumentSync(): Promise<void> {
  try {
    // Required in incremental document mode before subscribing to documentchange.
    await figma.loadAllPagesAsync();
    figma.on("documentchange", () => {
      scheduleFallbackSync();
    });
    isDocumentSyncReady = true;
  } catch (error) {
    isDocumentSyncReady = false;
    const message = error instanceof Error ? error.message : "Failed to initialize document sync.";
    figma.notify(`Connector sync fallback disabled: ${message}`);
    ensureFallbackPolling();
  }
}

function isImageNode(node: SceneNode): boolean {
  if (!("fills" in node)) {
    return false;
  }
  if (node.fills === figma.mixed || !Array.isArray(node.fills)) {
    return false;
  }
  return node.fills.some((fill) => fill.type === "IMAGE");
}

function isAutoLayoutNode(node: SceneNode): boolean {
  return "layoutMode" in node && node.layoutMode !== "NONE";
}

function isConnectorSide(value: unknown): value is ConnectorSide {
  return value === "LEFT" || value === "RIGHT" || value === "TOP" || value === "BOTTOM";
}

function isNodeType(value: unknown): value is NodeType {
  return value === "none" || value === "process" || value === "start-end" || value === "yes-no";
}

function isFrameOrImage(node: SceneNode): node is FrameLikeNode {
  if (!("x" in node) || !("width" in node)) {
    return false;
  }
  return node.type === "FRAME" || isImageNode(node) || isAutoLayoutNode(node);
}

function getAttachPoint(
  node: FrameLikeNode,
  side: ConnectorSide
): { x: number; y: number } {
  const bounds = getNodeBoundsInPage(node);
  if (side === "LEFT") {
    return { x: bounds.x, y: bounds.y + bounds.height / 2 };
  }
  if (side === "RIGHT") {
    return { x: bounds.x + bounds.width, y: bounds.y + bounds.height / 2 };
  }
  if (side === "TOP") {
    return { x: bounds.x + bounds.width / 2, y: bounds.y };
  }
  return { x: bounds.x + bounds.width / 2, y: bounds.y + bounds.height };
}

function getNodeBoundsInPage(node: FrameLikeNode): NodeBounds {
  return {
    x: node.absoluteTransform[0][2],
    y: node.absoluteTransform[1][2],
    width: node.width,
    height: node.height
  };
}

function isConnectorGroup(node: SceneNode): node is GroupNode {
  return node.type === "GROUP" && node.getPluginData(FALLBACK_LINK_MARK) === "true";
}

async function generateConnectorFromSelection(options?: { selected?: FrameLikeNode[]; notify?: boolean }): Promise<void> {
  const notify = options?.notify ?? true;
  const selected = options?.selected ?? figma.currentPage.selection.filter((node) => isFrameOrImage(node));
  if (selected.length !== 2) {
    throw new Error("Please select exactly 2 Frame/Image/Auto Layout nodes.");
  }

  updateSelectionOrder();
  const orderedSelection = resolveSelectionByOrder(selected);
  const [sourceNode, targetNode] = orderedSelection;
  const linkNode = createLinkBetweenNodes(
    sourceNode,
    targetNode,
    connectorPreference.sourceSide,
    connectorPreference.targetSide
  );
  figma.currentPage.selection = [sourceNode, targetNode, linkNode];
  if (notify) {
    figma.notify("Connector generated.");
  }
}

function getCurrentSelectablePair(): FrameLikeNode[] | null {
  const fullSelection = figma.currentPage.selection;
  if (fullSelection.length !== 2) {
    return null;
  }
  const selectable = fullSelection.filter((node) => isFrameOrImage(node));
  return selectable.length === 2 ? selectable : null;
}

async function maybeAutoGenerateConnector(): Promise<void> {
  if (isAutoGeneratingConnector) {
    return;
  }
  const pair = getCurrentSelectablePair();
  if (!pair) {
    lastAutoGeneratedPairKey = null;
    return;
  }

  const pairKey = `${pair
    .map((node) => node.id)
    .sort()
    .join("|")}::${connectorPreference.sourceSide}->${connectorPreference.targetSide}`;
  if (pairKey === lastAutoGeneratedPairKey) {
    return;
  }

  isAutoGeneratingConnector = true;
  try {
    await generateConnectorFromSelection({ selected: pair, notify: false });
    sendStatus("success", "Auto generated");
    lastAutoGeneratedPairKey = pairKey;
  } catch (error) {
    const message = error instanceof Error ? error.message : "Auto generation failed.";
    sendStatus("error", message);
  } finally {
    isAutoGeneratingConnector = false;
  }
}

async function maybeAutoInsertNodeFromConnector(): Promise<void> {
  if (isAutoInsertingNode) {
    return;
  }
  if (figma.currentPage.selection.length !== 1) {
    return;
  }
  const selected = figma.currentPage.selection[0];
  if (!isConnectorGroup(selected)) {
    return;
  }

  isAutoInsertingNode = true;
  try {
    await figma.loadFontAsync(FONT_REGULAR);
    await insertDefaultNodeOnConnector(selected);
    sendStatus("success", "Node inserted");
  } catch (error) {
    const message = error instanceof Error ? error.message : "Failed to insert node.";
    sendStatus("error", message);
  } finally {
    isAutoInsertingNode = false;
  }
}

function resolveSelectionByOrder(selected: FrameLikeNode[]): [FrameLikeNode, FrameLikeNode] {
  if (selected.length !== 2) {
    throw new Error("Selection must contain exactly two nodes.");
  }
  const [a, b] = selected;
  const indexA = frameSelectionOrder.indexOf(a.id);
  const indexB = frameSelectionOrder.indexOf(b.id);
  if (indexA === -1 || indexB === -1 || indexA === indexB) {
    return [a, b];
  }
  return indexA < indexB ? [a, b] : [b, a];
}

function updateSelectionOrder(): void {
  const currentIds = figma.currentPage.selection.filter((node) => isFrameOrImage(node)).map((node) => node.id);
  const currentSet = new Set(currentIds);

  frameSelectionOrder = frameSelectionOrder.filter((id) => currentSet.has(id));

  currentIds.forEach((id) => {
    if (!previousFrameSelection.has(id) || !frameSelectionOrder.includes(id)) {
      frameSelectionOrder.push(id);
    }
  });

  previousFrameSelection = currentSet;
}

function createLinkBetweenNodes(
  sourceNode: SceneNode & DimensionAndPositionMixin,
  targetNode: SceneNode & DimensionAndPositionMixin,
  sourceSide: ConnectorSide,
  targetSide: ConnectorSide
): SceneNode {
  // Always use deterministic shape rendering to guarantee endpoint placement.
  return createFallbackShapeLink(sourceNode, targetNode, sourceSide, targetSide);
}

async function insertDefaultNodeOnConnector(connector: GroupNode): Promise<void> {
  const startNodeId = connector.getPluginData(FALLBACK_LINK_START_ID);
  const endNodeId = connector.getPluginData(FALLBACK_LINK_END_ID);
  if (!startNodeId || !endNodeId) {
    throw new Error("Connector endpoints not found.");
  }

  const [startNode, endNode] = await Promise.all([
    figma.getNodeByIdAsync(startNodeId),
    figma.getNodeByIdAsync(endNodeId)
  ]);
  if (!startNode || !endNode || !("x" in startNode) || !("x" in endNode)) {
    throw new Error("Connected nodes no longer exist.");
  }

  const startFrame = startNode as FrameLikeNode;
  const endFrame = endNode as FrameLikeNode;
  const sourceSide = parseConnectorSide(connector.getPluginData(FALLBACK_LINK_SOURCE_SIDE), "RIGHT");
  const targetSide = parseConnectorSide(connector.getPluginData(FALLBACK_LINK_TARGET_SIDE), "LEFT");

  const startPoint = getAttachPoint(startFrame, sourceSide);
  const endPoint = getAttachPoint(endFrame, targetSide);
  const centerX = (startPoint.x + endPoint.x) / 2;
  const centerY = (startPoint.y + endPoint.y) / 2;

  const node = createBaseNodeAt(centerX, centerY);
  applyNodeType(node, "none", { mode: "default" });

  createLinkBetweenNodes(startFrame, node, sourceSide, oppositeSide(sourceSide));
  createLinkBetweenNodes(node, endFrame, oppositeSide(targetSide), targetSide);
  connector.remove();
  figma.currentPage.selection = [node];
}

async function applyNodeTypeToSelection(nodeType: NodeType): Promise<void> {
  await figma.loadFontAsync(FONT_REGULAR);
  if (figma.currentPage.selection.length !== 1) {
    throw new Error("Select exactly one Node to change type.");
  }
  const selected = figma.currentPage.selection[0];
  if (selected.type !== "FRAME" || selected.getPluginData(FLOW_NODE_MARK) !== "true") {
    throw new Error("Selected object is not a Flow Node.");
  }
  applyNodeType(selected, nodeType, { mode: "preserve" });
  emitNodeTypeState();
}

function createBaseNodeAt(centerX: number, centerY: number): FrameNode {
  const node = figma.createFrame();
  node.name = "Flow Node";
  node.fills = [{ type: "SOLID", color: hexToRgb("#FCFCFC") }];
  node.strokes = [{ type: "SOLID", color: hexToRgb("#383838") }];
  node.strokeWeight = 1.5;
  node.layoutMode = "NONE";
  node.clipsContent = false;
  figma.currentPage.appendChild(node);
  node.x = centerX - 66;
  node.y = centerY - 26;
  return node;
}

function getOrCreateNodeLabel(node: FrameNode): TextNode {
  const existing = node.findChild(
    (child): child is TextNode => child.type === "TEXT" && child.getPluginData(FLOW_NODE_LABEL_ROLE) === "true"
  );
  if (existing) {
    return existing;
  }
  const label = figma.createText();
  label.fontName = FONT_REGULAR;
  label.fontSize = 12;
  label.textAlignHorizontal = "CENTER";
  label.textAutoResize = "WIDTH_AND_HEIGHT";
  label.fills = [{ type: "SOLID", color: hexToRgb("#383838") }];
  label.setPluginData(FLOW_NODE_LABEL_ROLE, "true");
  node.appendChild(label);
  return label;
}

function getOrCreateProcessShape(node: FrameNode): VectorNode {
  const existing = node.findChild(
    (child): child is VectorNode => child.type === "VECTOR" && child.getPluginData(FLOW_NODE_PROCESS_SHAPE_ROLE) === "true"
  );
  if (existing) {
    return existing;
  }
  const shape = figma.createVector();
  shape.name = "Process Diamond";
  shape.setPluginData(FLOW_NODE_PROCESS_SHAPE_ROLE, "true");
  node.insertChild(0, shape);
  return shape;
}

function hideProcessShape(node: FrameNode): void {
  const shape = node.findChild(
    (child): child is VectorNode => child.type === "VECTOR" && child.getPluginData(FLOW_NODE_PROCESS_SHAPE_ROLE) === "true"
  );
  if (shape) {
    shape.visible = false;
  }
}

function applyNodeType(node: FrameNode, nodeType: NodeType, textBehavior: { mode: "default" | "preserve" }): void {
  const shouldPreserveCenter = textBehavior.mode === "preserve";
  const preservedCenterX = node.x + node.width / 2;
  const preservedCenterY = node.y + node.height / 2;

  node.layoutMode = "NONE";
  node.primaryAxisSizingMode = "AUTO";
  node.counterAxisSizingMode = "AUTO";
  node.paddingLeft = 0;
  node.paddingRight = 0;
  node.paddingTop = 0;
  node.paddingBottom = 0;
  node.itemSpacing = 0;
  node.rotation = 0;

  const label = getOrCreateNodeLabel(node);
  const defaults: Record<NodeType, string> = {
    none: "Text",
    process: "Text",
    "start-end": "Text",
    "yes-no": "Text"
  };
  if (textBehavior.mode === "default") {
    label.characters = defaults[nodeType];
  } else if (nodeType === "yes-no") {
    // Y/N node resets to its default text when applied.
    label.characters = defaults[nodeType];
  } else if (!label.characters || label.characters.trim().length === 0) {
    label.characters = defaults[nodeType];
  }

  switch (nodeType) {
    case "none": {
      node.name = "None Node";
      hideProcessShape(node);
      node.layoutMode = "VERTICAL";
      node.primaryAxisSizingMode = "AUTO";
      node.counterAxisSizingMode = "FIXED";
      node.primaryAxisAlignItems = "CENTER";
      node.counterAxisAlignItems = "CENTER";
      node.itemSpacing = 0;
      node.paddingLeft = 12;
      node.paddingRight = 12;
      node.paddingTop = 10;
      node.paddingBottom = 10;
      node.cornerRadius = 10;
      node.resize(132, 52);
      node.fills = [{ type: "SOLID", color: hexToRgb("#FCFCFC") }];
      node.strokes = [{ type: "SOLID", color: hexToRgb("#383838") }];
      node.strokeWeight = 1.5;
      label.rotation = 0;
      label.textAutoResize = "HEIGHT";
      label.resize(node.width - node.paddingLeft - node.paddingRight, Math.max(label.height, 16));
      label.x = node.paddingLeft;
      label.y = node.height / 2 - label.height / 2;
      break;
    }
    case "process": {
      node.name = "Process Node";
      node.layoutMode = "NONE";
      node.cornerRadius = 0;
      node.resize(180, 180);
      node.fills = [];
      node.strokes = [];

      const processShape = getOrCreateProcessShape(node);
      processShape.visible = true;
      processShape.vectorPaths = [{ windingRule: "NONZERO", data: "M 90 0 L 180 90 L 90 180 L 0 90 Z" }];
      processShape.fills = [{ type: "SOLID", color: hexToRgb("#FCFCFC") }];
      processShape.strokes = [{ type: "SOLID", color: hexToRgb("#383838") }];
      processShape.strokeWeight = 1.5;
      processShape.resize(180, 180);
      processShape.x = 0;
      processShape.y = 0;
      processShape.rotation = 0;

      label.rotation = 0;
      label.textAlignHorizontal = "CENTER";
      label.textAutoResize = "HEIGHT";
      label.resize(110, Math.max(label.height, 16));
      label.x = node.width / 2 - label.width / 2;
      label.y = node.height / 2 - label.height / 2;
      break;
    }
    case "start-end": {
      node.name = "Start/End Node";
      hideProcessShape(node);
      node.layoutMode = "VERTICAL";
      node.primaryAxisSizingMode = "FIXED";
      node.counterAxisSizingMode = "FIXED";
      node.primaryAxisAlignItems = "CENTER";
      node.counterAxisAlignItems = "CENTER";
      node.itemSpacing = 0;
      node.paddingLeft = 0;
      node.paddingRight = 0;
      node.paddingTop = 0;
      node.paddingBottom = 0;
      node.cornerRadius = 999;
      node.resize(132, 52);
      node.fills = [{ type: "SOLID", color: hexToRgb("#FCFCFC") }];
      node.strokes = [{ type: "SOLID", color: hexToRgb("#383838") }];
      node.strokeWeight = 1.5;
      label.rotation = 0;
      label.textAutoResize = "WIDTH_AND_HEIGHT";
      break;
    }
    case "yes-no": {
      node.name = "Y/N Node";
      hideProcessShape(node);
      node.layoutMode = "VERTICAL";
      node.primaryAxisSizingMode = "FIXED";
      node.counterAxisSizingMode = "FIXED";
      node.primaryAxisAlignItems = "CENTER";
      node.counterAxisAlignItems = "CENTER";
      node.itemSpacing = 0;
      node.paddingLeft = 0;
      node.paddingRight = 0;
      node.paddingTop = 0;
      node.paddingBottom = 0;
      node.cornerRadius = 6;
      node.resize(52, 52);
      node.fills = [{ type: "SOLID", color: hexToRgb("#FCFCFC") }];
      node.strokes = [{ type: "SOLID", color: hexToRgb("#383838") }];
      node.strokeWeight = 1.5;
      label.rotation = 0;
      label.textAutoResize = "WIDTH_AND_HEIGHT";
      break;
    }
    default:
      break;
  }

  if (shouldPreserveCenter) {
    node.x = preservedCenterX - node.width / 2;
    node.y = preservedCenterY - node.height / 2;
  }

  node.setPluginData(FLOW_NODE_MARK, "true");
  node.setPluginData("flow-builder-node-type", nodeType);
}

function createFallbackShapeLink(
  sourceNode: SceneNode & DimensionAndPositionMixin,
  targetNode: SceneNode & DimensionAndPositionMixin,
  sourceSide: ConnectorSide,
  targetSide: ConnectorSide
): GroupNode {
  const container = figma.createFrame();
  container.name = "_flow-connector-internal";
  container.fills = [];
  container.strokes = [];
  container.clipsContent = false;
  container.resize(10, 10);
  container.setPluginData(FALLBACK_CONTAINER_ROLE, "true");
  figma.currentPage.appendChild(container);

  const segment1 = figma.createRectangle();
  segment1.name = "Flow Link Segment";
  segment1.resize(10, 3);
  segment1.fills = [{ type: "SOLID", color: hexToRgb("#383838") }];
  segment1.strokes = [];
  segment1.setPluginData(FALLBACK_ROLE_KEY, "segment-1");
  container.appendChild(segment1);

  const segment3 = figma.createRectangle();
  segment3.name = "Flow Link Segment";
  segment3.resize(10, 3);
  segment3.fills = [{ type: "SOLID", color: hexToRgb("#383838") }];
  segment3.strokes = [];
  segment3.setPluginData(FALLBACK_ROLE_KEY, "segment-3");
  container.appendChild(segment3);

  const segment2 = figma.createRectangle();
  segment2.name = "Flow Link Segment";
  segment2.resize(3, 10);
  segment2.fills = [{ type: "SOLID", color: hexToRgb("#383838") }];
  segment2.strokes = [];
  segment2.setPluginData(FALLBACK_ROLE_KEY, "segment-2");
  container.appendChild(segment2);

  const arrow = figma.createVector();
  arrow.name = "Flow Arrow";
  arrow.vectorPaths = [
    {
      windingRule: "NONZERO",
      data: getArrowPath(targetSide)
    }
  ];
  arrow.fills = [{ type: "SOLID", color: hexToRgb("#383838") }];
  arrow.strokes = [];
  arrow.resize(10, 10);
  arrow.setPluginData(FALLBACK_ROLE_KEY, "arrow");
  container.appendChild(arrow);

  const debugStart = figma.createEllipse();
  debugStart.name = "Debug Start";
  debugStart.resize(6, 6);
  debugStart.fills = [{ type: "SOLID", color: hexToRgb("#ff0066") }];
  debugStart.strokes = [];
  debugStart.setPluginData(FALLBACK_ROLE_KEY, "debug-start");
  debugStart.visible = debugEnabled;
  container.appendChild(debugStart);

  const debugMid = figma.createEllipse();
  debugMid.name = "Debug Mid";
  debugMid.resize(6, 6);
  debugMid.fills = [{ type: "SOLID", color: hexToRgb("#00a3ff") }];
  debugMid.strokes = [];
  debugMid.setPluginData(FALLBACK_ROLE_KEY, "debug-mid");
  debugMid.visible = debugEnabled;
  container.appendChild(debugMid);

  const debugEnd = figma.createEllipse();
  debugEnd.name = "Debug End";
  debugEnd.resize(6, 6);
  debugEnd.fills = [{ type: "SOLID", color: hexToRgb("#00c853") }];
  debugEnd.strokes = [];
  debugEnd.setPluginData(FALLBACK_ROLE_KEY, "debug-end");
  debugEnd.visible = debugEnabled;
  container.appendChild(debugEnd);

  const wrapper = figma.group([container], figma.currentPage);
  wrapper.name = "\u200B";
  wrapper.setPluginData(FALLBACK_LINK_MARK, "true");
  wrapper.setPluginData(FALLBACK_LINK_START_ID, sourceNode.id);
  wrapper.setPluginData(FALLBACK_LINK_END_ID, targetNode.id);
  wrapper.setPluginData(FALLBACK_LINK_SOURCE_SIDE, sourceSide);
  wrapper.setPluginData(FALLBACK_LINK_TARGET_SIDE, targetSide);
  layoutFallbackShapeLink(wrapper, sourceNode, targetNode, sourceSide, targetSide);
  return wrapper;
}

function layoutFallbackShapeLink(
  wrapper: GroupNode,
  sourceNode: SceneNode & DimensionAndPositionMixin,
  targetNode: SceneNode & DimensionAndPositionMixin,
  sourceSide: ConnectorSide,
  targetSide: ConnectorSide
): void {
  const container = getFallbackContainer(wrapper);
  if (!container) {
    return;
  }
  const segment1 = findFallbackChild<RectangleNode>(container, "segment-1", "RECTANGLE");
  const segment2 = findFallbackChild<RectangleNode>(container, "segment-2", "RECTANGLE");
  const segment3 = findFallbackChild<RectangleNode>(container, "segment-3", "RECTANGLE");
  const arrow = findFallbackChild<VectorNode>(container, "arrow", "VECTOR");
  const debugStart = findFallbackChild<EllipseNode>(container, "debug-start", "ELLIPSE");
  const debugMid = findFallbackChild<EllipseNode>(container, "debug-mid", "ELLIPSE");
  const debugEnd = findFallbackChild<EllipseNode>(container, "debug-end", "ELLIPSE");
  if (!segment1 || !segment2 || !segment3 || !arrow) {
    return;
  }

  const startPoint = getAttachPoint(sourceNode, sourceSide);
  const endPoint = getAttachPoint(targetNode, targetSide);

  const arrowLength = 10;
  const stroke = 3;
  const pathEnd = getPathEndBeforeArrow(endPoint, targetSide, arrowLength);
  const route = buildOrthogonalRoute(startPoint, pathEnd, sourceSide, targetSide);
  const segment1Abs = getSegmentRect(route[0], route[1], stroke);
  const segment2Abs = getSegmentRect(route[1], route[2], stroke);
  const segment3Abs = getSegmentRect(route[2], route[3], stroke);
  const arrowPath = getArrowPath(targetSide);
  const arrowAbs = getArrowRect(endPoint, targetSide, arrowLength);
  const debugStartAbs = { x: startPoint.x - 3, y: startPoint.y - 3, w: 6, h: 6 };
  const debugMidAbs = { x: route[1].x - 3, y: route[1].y - 3, w: 6, h: 6 };
  const debugEndAbs = { x: endPoint.x - 3, y: endPoint.y - 3, w: 6, h: 6 };

  const minX = Math.min(
    segment1Abs.x,
    segment2Abs.x,
    segment3Abs.x,
    arrowAbs.x,
    debugStartAbs.x,
    debugMidAbs.x,
    debugEndAbs.x
  );
  const minY = Math.min(
    segment1Abs.y,
    segment2Abs.y,
    segment3Abs.y,
    arrowAbs.y,
    debugStartAbs.y,
    debugMidAbs.y,
    debugEndAbs.y
  );

  // Keep geometry anchored by the internal frame only.
  // Group is just an outer wrapper for layer organization.
  maybeSetPosition(container, minX, minY);
  const containerWidth = Math.max(
    segment1Abs.x + segment1Abs.w,
    segment2Abs.x + segment2Abs.w,
    segment3Abs.x + segment3Abs.w,
    arrowAbs.x + arrowAbs.w,
    debugStartAbs.x + debugStartAbs.w,
    debugMidAbs.x + debugMidAbs.w,
    debugEndAbs.x + debugEndAbs.w
  ) - minX;
  const containerHeight = Math.max(
    segment1Abs.y + segment1Abs.h,
    segment2Abs.y + segment2Abs.h,
    segment3Abs.y + segment3Abs.h,
    arrowAbs.y + arrowAbs.h,
    debugStartAbs.y + debugStartAbs.h,
    debugMidAbs.y + debugMidAbs.h,
    debugEndAbs.y + debugEndAbs.h
  ) - minY;
  if (!almostEqual(container.width, containerWidth) || !almostEqual(container.height, containerHeight)) {
    container.resize(containerWidth, containerHeight);
  }

  maybeSetRectGeometry(segment1, segment1Abs.x - minX, segment1Abs.y - minY, segment1Abs.w, segment1Abs.h);
  maybeSetRectGeometry(segment2, segment2Abs.x - minX, segment2Abs.y - minY, segment2Abs.w, segment2Abs.h);
  maybeSetRectGeometry(segment3, segment3Abs.x - minX, segment3Abs.y - minY, segment3Abs.w, segment3Abs.h);

  arrow.vectorPaths = [{ windingRule: "NONZERO", data: arrowPath }];
  maybeSetVectorGeometry(arrow, arrowAbs.x - minX, arrowAbs.y - minY, arrowAbs.w, arrowAbs.h, 0);

  if (debugStart && debugMid && debugEnd) {
    maybeSetEllipseGeometry(debugStart, debugStartAbs.x - minX, debugStartAbs.y - minY, debugStartAbs.w, debugStartAbs.h);
    maybeSetEllipseGeometry(debugMid, debugMidAbs.x - minX, debugMidAbs.y - minY, debugMidAbs.w, debugMidAbs.h);
    maybeSetEllipseGeometry(debugEnd, debugEndAbs.x - minX, debugEndAbs.y - minY, debugEndAbs.w, debugEndAbs.h);
    debugStart.visible = debugEnabled;
    debugMid.visible = debugEnabled;
    debugEnd.visible = debugEnabled;
  }
}

function findFallbackChild<T extends SceneNode>(
  container: FrameNode,
  role: string,
  type: SceneNode["type"]
): T | null {
  const node = container.children.find((child) => child.type === type && child.getPluginData(FALLBACK_ROLE_KEY) === role);
  return (node as T | undefined) ?? null;
}

function getFallbackContainer(wrapper: GroupNode): FrameNode | null {
  const container = wrapper.children.find(
    (child): child is FrameNode => child.type === "FRAME" && child.getPluginData(FALLBACK_CONTAINER_ROLE) === "true"
  );
  return container ?? null;
}

function parseConnectorSide(value: string, fallback: ConnectorSide): ConnectorSide {
  return isConnectorSide(value) ? value : fallback;
}

function oppositeSide(side: ConnectorSide): ConnectorSide {
  switch (side) {
    case "LEFT":
      return "RIGHT";
    case "RIGHT":
      return "LEFT";
    case "TOP":
      return "BOTTOM";
    case "BOTTOM":
      return "TOP";
    default:
      return "RIGHT";
  }
}

function isHorizontalSide(side: ConnectorSide): boolean {
  return side === "LEFT" || side === "RIGHT";
}

function buildOrthogonalRoute(
  startPoint: { x: number; y: number },
  endPoint: { x: number; y: number },
  sourceSide: ConnectorSide,
  targetSide: ConnectorSide
): [{ x: number; y: number }, { x: number; y: number }, { x: number; y: number }, { x: number; y: number }] {
  const sourceIsHorizontal = isHorizontalSide(sourceSide);
  const targetIsHorizontal = isHorizontalSide(targetSide);

  if (sourceIsHorizontal && targetIsHorizontal) {
    const midX = (startPoint.x + endPoint.x) / 2;
    return [
      startPoint,
      { x: midX, y: startPoint.y },
      { x: midX, y: endPoint.y },
      endPoint
    ];
  }

  if (!sourceIsHorizontal && !targetIsHorizontal) {
    const midY = (startPoint.y + endPoint.y) / 2;
    return [
      startPoint,
      { x: startPoint.x, y: midY },
      { x: endPoint.x, y: midY },
      endPoint
    ];
  }

  if (!sourceIsHorizontal && targetIsHorizontal) {
    return [
      startPoint,
      { x: startPoint.x, y: endPoint.y },
      { x: endPoint.x, y: endPoint.y },
      endPoint
    ];
  }

  return [
    startPoint,
    { x: endPoint.x, y: startPoint.y },
    { x: endPoint.x, y: endPoint.y },
    endPoint
  ];
}

function getPathEndBeforeArrow(endPoint: { x: number; y: number }, targetSide: ConnectorSide, arrowLength: number): {
  x: number;
  y: number;
} {
  const arrowDirection = oppositeSide(targetSide);
  switch (arrowDirection) {
    case "LEFT":
      return { x: endPoint.x + arrowLength, y: endPoint.y };
    case "RIGHT":
      return { x: endPoint.x - arrowLength, y: endPoint.y };
    case "TOP":
      return { x: endPoint.x, y: endPoint.y + arrowLength };
    case "BOTTOM":
      return { x: endPoint.x, y: endPoint.y - arrowLength };
    default:
      return { x: endPoint.x - arrowLength, y: endPoint.y };
  }
}

function getArrowPath(targetSide: ConnectorSide): string {
  const arrowDirection = oppositeSide(targetSide);
  switch (arrowDirection) {
    case "LEFT":
      return "M 10 0 L 0 5 L 10 10 Z";
    case "RIGHT":
      return "M 0 0 L 10 5 L 0 10 Z";
    case "TOP":
      return "M 0 10 L 5 0 L 10 10 Z";
    case "BOTTOM":
      return "M 0 0 L 5 10 L 10 0 Z";
    default:
      return "M 0 0 L 10 5 L 0 10 Z";
  }
}

function getArrowRect(endPoint: { x: number; y: number }, targetSide: ConnectorSide, arrowLength: number): {
  x: number;
  y: number;
  w: number;
  h: number;
} {
  const arrowDirection = oppositeSide(targetSide);
  switch (arrowDirection) {
    case "LEFT":
      return { x: endPoint.x, y: endPoint.y - 5, w: arrowLength, h: arrowLength };
    case "RIGHT":
      return { x: endPoint.x - arrowLength, y: endPoint.y - 5, w: arrowLength, h: arrowLength };
    case "TOP":
      return { x: endPoint.x - 5, y: endPoint.y, w: arrowLength, h: arrowLength };
    case "BOTTOM":
      return { x: endPoint.x - 5, y: endPoint.y - arrowLength, w: arrowLength, h: arrowLength };
    default:
      return { x: endPoint.x - arrowLength, y: endPoint.y - 5, w: arrowLength, h: arrowLength };
  }
}

function getSegmentRect(
  from: { x: number; y: number },
  to: { x: number; y: number },
  stroke: number
): { x: number; y: number; w: number; h: number } {
  const isHorizontal = Math.abs(from.y - to.y) <= GEOMETRY_EPSILON;
  if (isHorizontal) {
    return {
      x: Math.min(from.x, to.x),
      y: from.y - stroke / 2,
      w: Math.max(Math.abs(to.x - from.x), 2),
      h: stroke
    };
  }
  return {
    x: from.x - stroke / 2,
    y: Math.min(from.y, to.y),
    w: stroke,
    h: Math.max(Math.abs(to.y - from.y), 2)
  };
}

async function syncFallbackLinks(): Promise<void> {
  if (isSyncingFallbackLinks) {
    return;
  }
  isSyncingFallbackLinks = true;
  try {
    const links = figma.currentPage.findAll(
      (node): node is GroupNode => node.type === "GROUP" && node.getPluginData(FALLBACK_LINK_MARK) === "true"
    );
    if (links.length === 0) {
      return;
    }
    for (const wrapper of links) {
      const startNodeId = wrapper.getPluginData(FALLBACK_LINK_START_ID);
      const endNodeId = wrapper.getPluginData(FALLBACK_LINK_END_ID);
      if (!startNodeId || !endNodeId) {
        continue;
      }

      const [startNode, endNode] = await Promise.all([
        figma.getNodeByIdAsync(startNodeId),
        figma.getNodeByIdAsync(endNodeId)
      ]);
      if (!startNode || !endNode || !("x" in startNode) || !("x" in endNode)) {
        continue;
      }

      const startDim = startNode as SceneNode & DimensionAndPositionMixin;
      const endDim = endNode as SceneNode & DimensionAndPositionMixin;
      const sourceSide = parseConnectorSide(wrapper.getPluginData(FALLBACK_LINK_SOURCE_SIDE), "RIGHT");
      const targetSide = parseConnectorSide(wrapper.getPluginData(FALLBACK_LINK_TARGET_SIDE), "LEFT");
      layoutFallbackShapeLink(wrapper, startDim, endDim, sourceSide, targetSide);
    }
  } finally {
    isSyncingFallbackLinks = false;
  }
}

function scheduleFallbackSync(): void {
  if (pendingSyncTimer) {
    return;
  }
  pendingSyncTimer = setTimeout(() => {
    pendingSyncTimer = null;
    void syncFallbackLinks();
  }, SYNC_THROTTLE_MS);
}

function ensureFallbackPolling(): void {
  // Use polling only as a fallback when documentchange sync is unavailable.
  if (isDocumentSyncReady) {
    return;
  }
  if (fallbackPollingTimer) {
    return;
  }
  fallbackPollingTimer = setInterval(() => {
    void syncFallbackLinks();
  }, POLLING_SYNC_MS);
}

function applyDebugVisibilityToAllLinks(): void {
  const links = figma.currentPage.findAll(
    (node): node is GroupNode => node.type === "GROUP" && node.getPluginData(FALLBACK_LINK_MARK) === "true"
  );
  for (const wrapper of links) {
    const container = getFallbackContainer(wrapper);
    if (!container) {
      continue;
    }
    const debugStart = findFallbackChild<EllipseNode>(container, "debug-start", "ELLIPSE");
    const debugMid = findFallbackChild<EllipseNode>(container, "debug-mid", "ELLIPSE");
    const debugEnd = findFallbackChild<EllipseNode>(container, "debug-end", "ELLIPSE");
    if (debugStart) {
      debugStart.visible = debugEnabled;
    }
    if (debugMid) {
      debugMid.visible = debugEnabled;
    }
    if (debugEnd) {
      debugEnd.visible = debugEnabled;
    }
  }
}

function almostEqual(a: number, b: number): boolean {
  return Math.abs(a - b) <= GEOMETRY_EPSILON;
}

function maybeSetPosition(node: SceneNode & DimensionAndPositionMixin, x: number, y: number): void {
  if (!almostEqual(node.x, x)) {
    node.x = x;
  }
  if (!almostEqual(node.y, y)) {
    node.y = y;
  }
}

function maybeSetRectGeometry(node: RectangleNode, x: number, y: number, w: number, h: number): void {
  maybeSetPosition(node, x, y);
  if (!almostEqual(node.width, w) || !almostEqual(node.height, h)) {
    node.resize(w, h);
  }
}

function maybeSetEllipseGeometry(node: EllipseNode, x: number, y: number, w: number, h: number): void {
  maybeSetPosition(node, x, y);
  if (!almostEqual(node.width, w) || !almostEqual(node.height, h)) {
    node.resize(w, h);
  }
}

function maybeSetVectorGeometry(
  node: VectorNode,
  x: number,
  y: number,
  w: number,
  h: number,
  rotation: number
): void {
  maybeSetPosition(node, x, y);
  if (!almostEqual(node.width, w) || !almostEqual(node.height, h)) {
    node.resize(w, h);
  }
  if (!almostEqual(node.rotation, rotation)) {
    node.rotation = rotation;
  }
}

function hexToRgb(hex: string): RGB {
  const cleanHex = hex.replace("#", "");
  const parsed = parseInt(cleanHex, 16);
  return {
    r: ((parsed >> 16) & 255) / 255,
    g: ((parsed >> 8) & 255) / 255,
    b: (parsed & 255) / 255
  };
}

function sendStatus(kind: "success" | "error", message: string): void {
  figma.ui.postMessage({
    type: "status",
    payload: {
      kind,
      message
    }
  });
}
