figma.showUI(__html__, { width: 360, height: 300 });

type PluginRequest = { type: "generate-connector" } | { type: "set-debug"; payload: { enabled: boolean } };
type HorizontalMagnet = "LEFT" | "RIGHT";
type FrameLikeNode = SceneNode & DimensionAndPositionMixin;
type NodeBounds = { x: number; y: number; width: number; height: number };

let previousFrameSelection = new Set<string>();
let frameSelectionOrder: string[] = [];
let isSyncingFallbackLinks = false;
let pendingSyncTimer: ReturnType<typeof setTimeout> | null = null;
let fallbackPollingTimer: ReturnType<typeof setInterval> | null = null;
let debugEnabled = false;
let isAutoGeneratingConnector = false;
let lastAutoGeneratedPairKey: string | null = null;

const FALLBACK_LINK_MARK = "flow-builder-fallback-link";
const FALLBACK_LINK_START_ID = "flow-builder-fallback-start-id";
const FALLBACK_LINK_END_ID = "flow-builder-fallback-end-id";
const FALLBACK_ROLE_KEY = "flow-builder-fallback-role";
const FALLBACK_CONTAINER_ROLE = "flow-builder-container";
const FALLBACK_DEBUG_ENABLED = "flow-builder-debug-enabled";
const SYNC_THROTTLE_MS = 33;
const GEOMETRY_EPSILON = 0.25;
const POLLING_SYNC_MS = 250;

figma.ui.onmessage = async (msg: PluginRequest) => {
  try {
    if (msg.type === "generate-connector") {
      await generateConnectorFromSelection();
      sendStatus("success", "Successful");
      return;
    }
    if (msg.type === "set-debug") {
      debugEnabled = msg.payload.enabled;
      await figma.clientStorage.setAsync(FALLBACK_DEBUG_ENABLED, debugEnabled);
      applyDebugVisibilityToAllLinks();
      emitDebugState();
      sendStatus("success", debugEnabled ? "Debug ON" : "Debug OFF");
      return;
    }
    throw new Error("Unsupported command.");
  } catch (error) {
    const message = error instanceof Error ? error.message : "Unexpected plugin error.";
    figma.notify(message, { error: true });
    sendStatus("error", message);
  }
};

figma.on("selectionchange", () => {
  updateSelectionOrder();
  void maybeAutoGenerateConnector();
});

void initializeSettings();
void initializeDocumentSync();

async function initializeSettings(): Promise<void> {
  try {
    const storedDebug = await figma.clientStorage.getAsync(FALLBACK_DEBUG_ENABLED);
    debugEnabled = storedDebug === true;
    emitDebugState();
    setTimeout(() => emitDebugState(), 300);
  } catch {
    debugEnabled = false;
  }
}

function emitDebugState(): void {
  figma.ui.postMessage({ type: "debug-state", payload: { enabled: debugEnabled } });
}

async function initializeDocumentSync(): Promise<void> {
  try {
    // Required in incremental document mode before subscribing to documentchange.
    await figma.loadAllPagesAsync();
    figma.on("documentchange", () => {
      scheduleFallbackSync();
    });
  } catch (error) {
    const message = error instanceof Error ? error.message : "Failed to initialize document sync.";
    figma.notify(`Connector sync fallback disabled: ${message}`);
    ensureFallbackPolling();
  }
}

function isImageNode(node: SceneNode): boolean {
  if (!("fills" in node)) {
    return false;
  }
  if (node.fills === figma.mixed || !Array.isArray(node.fills)) {
    return false;
  }
  return node.fills.some((fill) => fill.type === "IMAGE");
}

function isFrameOrImage(node: SceneNode): node is FrameLikeNode {
  if (!("x" in node) || !("width" in node)) {
    return false;
  }
  return node.type === "FRAME" || isImageNode(node);
}

function getAttachPoint(
  node: FrameLikeNode,
  magnet: HorizontalMagnet
): { x: number; y: number } {
  const bounds = getNodeBoundsInPage(node);
  if (magnet === "LEFT") {
    return { x: bounds.x, y: bounds.y + bounds.height / 2 };
  }
  return { x: bounds.x + bounds.width, y: bounds.y + bounds.height / 2 };
}

function getNodeBoundsInPage(node: FrameLikeNode): NodeBounds {
  return {
    x: node.absoluteTransform[0][2],
    y: node.absoluteTransform[1][2],
    width: node.width,
    height: node.height
  };
}

async function generateConnectorFromSelection(options?: { selected?: FrameLikeNode[]; notify?: boolean }): Promise<void> {
  const notify = options?.notify ?? true;
  const selected = options?.selected ?? figma.currentPage.selection.filter((node) => isFrameOrImage(node));
  if (selected.length !== 2) {
    throw new Error("Please select exactly 2 Frame/Image nodes.");
  }

  updateSelectionOrder();
  const orderedSelection = resolveSelectionByOrder(selected);
  const [sourceNode, targetNode] = orderedSelection;
  const sourceBounds = getNodeBoundsInPage(sourceNode);
  const targetBounds = getNodeBoundsInPage(targetNode);
  const direction: HorizontalMagnet =
    targetBounds.x + targetBounds.width / 2 >= sourceBounds.x + sourceBounds.width / 2 ? "RIGHT" : "LEFT";

  const linkNode = createLinkBetweenNodes(sourceNode, targetNode, direction);
  figma.currentPage.selection = [sourceNode, targetNode, linkNode];
  if (notify) {
    figma.notify(`Connector generated (${direction === "RIGHT" ? "rightward" : "leftward"}).`);
  }
  ensureFallbackPolling();
}

function getCurrentSelectablePair(): FrameLikeNode[] | null {
  const fullSelection = figma.currentPage.selection;
  if (fullSelection.length !== 2) {
    return null;
  }
  const selectable = fullSelection.filter((node) => isFrameOrImage(node));
  return selectable.length === 2 ? selectable : null;
}

async function maybeAutoGenerateConnector(): Promise<void> {
  if (isAutoGeneratingConnector) {
    return;
  }
  const pair = getCurrentSelectablePair();
  if (!pair) {
    lastAutoGeneratedPairKey = null;
    return;
  }

  const pairKey = pair.map((node) => node.id).sort().join("|");
  if (pairKey === lastAutoGeneratedPairKey) {
    return;
  }

  isAutoGeneratingConnector = true;
  try {
    await generateConnectorFromSelection({ selected: pair, notify: false });
    sendStatus("success", "Auto generated");
    lastAutoGeneratedPairKey = pairKey;
  } catch (error) {
    const message = error instanceof Error ? error.message : "Auto generation failed.";
    sendStatus("error", message);
  } finally {
    isAutoGeneratingConnector = false;
  }
}

function resolveSelectionByOrder(selected: FrameLikeNode[]): [FrameLikeNode, FrameLikeNode] {
  if (selected.length !== 2) {
    throw new Error("Selection must contain exactly two nodes.");
  }
  const [a, b] = selected;
  const indexA = frameSelectionOrder.indexOf(a.id);
  const indexB = frameSelectionOrder.indexOf(b.id);
  if (indexA === -1 || indexB === -1 || indexA === indexB) {
    return [a, b];
  }
  return indexA < indexB ? [a, b] : [b, a];
}

function updateSelectionOrder(): void {
  const currentIds = figma.currentPage.selection.filter((node) => isFrameOrImage(node)).map((node) => node.id);
  const currentSet = new Set(currentIds);

  frameSelectionOrder = frameSelectionOrder.filter((id) => currentSet.has(id));

  currentIds.forEach((id) => {
    if (!previousFrameSelection.has(id) || !frameSelectionOrder.includes(id)) {
      frameSelectionOrder.push(id);
    }
  });

  previousFrameSelection = currentSet;
}

function createLinkBetweenNodes(
  sourceNode: SceneNode & DimensionAndPositionMixin,
  targetNode: SceneNode & DimensionAndPositionMixin,
  direction: HorizontalMagnet
): SceneNode {
  // Always use deterministic shape rendering to guarantee endpoint placement.
  return createFallbackShapeLink(sourceNode, targetNode, direction);
}

function createFallbackShapeLink(
  sourceNode: SceneNode & DimensionAndPositionMixin,
  targetNode: SceneNode & DimensionAndPositionMixin,
  direction: HorizontalMagnet
): GroupNode {
  const container = figma.createFrame();
  container.name = "_flow-connector-internal";
  container.fills = [];
  container.strokes = [];
  container.clipsContent = false;
  container.resize(10, 10);
  container.setPluginData(FALLBACK_CONTAINER_ROLE, "true");
  figma.currentPage.appendChild(container);

  const segment1 = figma.createRectangle();
  segment1.name = "Flow Link Segment";
  segment1.resize(10, 3);
  segment1.fills = [{ type: "SOLID", color: hexToRgb("#383838") }];
  segment1.strokes = [];
  segment1.setPluginData(FALLBACK_ROLE_KEY, "segment-1");
  container.appendChild(segment1);

  const segment3 = figma.createRectangle();
  segment3.name = "Flow Link Segment";
  segment3.resize(10, 3);
  segment3.fills = [{ type: "SOLID", color: hexToRgb("#383838") }];
  segment3.strokes = [];
  segment3.setPluginData(FALLBACK_ROLE_KEY, "segment-3");
  container.appendChild(segment3);

  const segment2 = figma.createRectangle();
  segment2.name = "Flow Link Segment";
  segment2.resize(3, 10);
  segment2.fills = [{ type: "SOLID", color: hexToRgb("#383838") }];
  segment2.strokes = [];
  segment2.setPluginData(FALLBACK_ROLE_KEY, "segment-2");
  container.appendChild(segment2);

  const arrow = figma.createVector();
  arrow.name = "Flow Arrow";
  arrow.vectorPaths = [
    {
      windingRule: "NONZERO",
      data: direction === "RIGHT" ? "M 0 0 L 10 5 L 0 10 Z" : "M 10 0 L 0 5 L 10 10 Z"
    }
  ];
  arrow.fills = [{ type: "SOLID", color: hexToRgb("#383838") }];
  arrow.strokes = [];
  arrow.resize(10, 10);
  arrow.setPluginData(FALLBACK_ROLE_KEY, "arrow");
  container.appendChild(arrow);

  const debugStart = figma.createEllipse();
  debugStart.name = "Debug Start";
  debugStart.resize(6, 6);
  debugStart.fills = [{ type: "SOLID", color: hexToRgb("#ff0066") }];
  debugStart.strokes = [];
  debugStart.setPluginData(FALLBACK_ROLE_KEY, "debug-start");
  debugStart.visible = debugEnabled;
  container.appendChild(debugStart);

  const debugMid = figma.createEllipse();
  debugMid.name = "Debug Mid";
  debugMid.resize(6, 6);
  debugMid.fills = [{ type: "SOLID", color: hexToRgb("#00a3ff") }];
  debugMid.strokes = [];
  debugMid.setPluginData(FALLBACK_ROLE_KEY, "debug-mid");
  debugMid.visible = debugEnabled;
  container.appendChild(debugMid);

  const debugEnd = figma.createEllipse();
  debugEnd.name = "Debug End";
  debugEnd.resize(6, 6);
  debugEnd.fills = [{ type: "SOLID", color: hexToRgb("#00c853") }];
  debugEnd.strokes = [];
  debugEnd.setPluginData(FALLBACK_ROLE_KEY, "debug-end");
  debugEnd.visible = debugEnabled;
  container.appendChild(debugEnd);

  const wrapper = figma.group([container], figma.currentPage);
  wrapper.name = "\u200B";
  wrapper.setPluginData(FALLBACK_LINK_MARK, "true");
  wrapper.setPluginData(FALLBACK_LINK_START_ID, sourceNode.id);
  wrapper.setPluginData(FALLBACK_LINK_END_ID, targetNode.id);
  layoutFallbackShapeLink(wrapper, sourceNode, targetNode, direction);
  return wrapper;
}

function layoutFallbackShapeLink(
  wrapper: GroupNode,
  sourceNode: SceneNode & DimensionAndPositionMixin,
  targetNode: SceneNode & DimensionAndPositionMixin,
  direction: HorizontalMagnet
): void {
  const container = getFallbackContainer(wrapper);
  if (!container) {
    return;
  }
  const segment1 = findFallbackChild<RectangleNode>(container, "segment-1", "RECTANGLE");
  const segment2 = findFallbackChild<RectangleNode>(container, "segment-2", "RECTANGLE");
  const segment3 = findFallbackChild<RectangleNode>(container, "segment-3", "RECTANGLE");
  const arrow = findFallbackChild<VectorNode>(container, "arrow", "VECTOR");
  const debugStart = findFallbackChild<EllipseNode>(container, "debug-start", "ELLIPSE");
  const debugMid = findFallbackChild<EllipseNode>(container, "debug-mid", "ELLIPSE");
  const debugEnd = findFallbackChild<EllipseNode>(container, "debug-end", "ELLIPSE");
  if (!segment1 || !segment2 || !segment3 || !arrow) {
    return;
  }

  const startPoint = getAttachPoint(sourceNode, direction === "RIGHT" ? "RIGHT" : "LEFT");
  const endPoint = getAttachPoint(targetNode, direction === "RIGHT" ? "LEFT" : "RIGHT");

  const arrowLength = 10;
  const stroke = 3;
  const travelDistance = endPoint.x - startPoint.x;
  const arrowInset = direction === "RIGHT" ? -arrowLength : arrowLength;
  const finalX = startPoint.x + travelDistance + arrowInset;
  const midX = startPoint.x + (finalX - startPoint.x) / 2;

  const segment1Abs = {
    x: Math.min(startPoint.x, midX),
    y: startPoint.y - stroke / 2,
    w: Math.max(Math.abs(midX - startPoint.x), 2),
    h: stroke
  };
  const segment2Abs = {
    x: midX - stroke / 2,
    y: Math.min(startPoint.y, endPoint.y),
    w: stroke,
    h: Math.max(Math.abs(endPoint.y - startPoint.y), 0.01)
  };
  const segment3Abs = {
    x: Math.min(midX, finalX),
    y: endPoint.y - stroke / 2,
    w: Math.max(Math.abs(finalX - midX), 2),
    h: stroke
  };
  const arrowPath = direction === "RIGHT" ? "M 0 0 L 10 5 L 0 10 Z" : "M 10 0 L 0 5 L 10 10 Z";
  const arrowAbs = {
    x: direction === "RIGHT" ? endPoint.x - arrowLength : endPoint.x,
    y: endPoint.y - 5,
    w: 10,
    h: 10
  };
  const debugStartAbs = { x: startPoint.x - 3, y: startPoint.y - 3, w: 6, h: 6 };
  const debugMidAbs = { x: midX - 3, y: endPoint.y - 3, w: 6, h: 6 };
  const debugEndAbs = { x: endPoint.x - 3, y: endPoint.y - 3, w: 6, h: 6 };

  const minX = Math.min(
    segment1Abs.x,
    segment2Abs.x,
    segment3Abs.x,
    arrowAbs.x,
    debugStartAbs.x,
    debugMidAbs.x,
    debugEndAbs.x
  );
  const minY = Math.min(
    segment1Abs.y,
    segment2Abs.y,
    segment3Abs.y,
    arrowAbs.y,
    debugStartAbs.y,
    debugMidAbs.y,
    debugEndAbs.y
  );

  // Keep geometry anchored by the internal frame only.
  // Group is just an outer wrapper for layer organization.
  maybeSetPosition(container, minX, minY);
  const containerWidth = Math.max(
    segment1Abs.x + segment1Abs.w,
    segment2Abs.x + segment2Abs.w,
    segment3Abs.x + segment3Abs.w,
    arrowAbs.x + arrowAbs.w,
    debugStartAbs.x + debugStartAbs.w,
    debugMidAbs.x + debugMidAbs.w,
    debugEndAbs.x + debugEndAbs.w
  ) - minX;
  const containerHeight = Math.max(
    segment1Abs.y + segment1Abs.h,
    segment2Abs.y + segment2Abs.h,
    segment3Abs.y + segment3Abs.h,
    arrowAbs.y + arrowAbs.h,
    debugStartAbs.y + debugStartAbs.h,
    debugMidAbs.y + debugMidAbs.h,
    debugEndAbs.y + debugEndAbs.h
  ) - minY;
  if (!almostEqual(container.width, containerWidth) || !almostEqual(container.height, containerHeight)) {
    container.resize(containerWidth, containerHeight);
  }

  maybeSetRectGeometry(segment1, segment1Abs.x - minX, segment1Abs.y - minY, segment1Abs.w, segment1Abs.h);
  maybeSetRectGeometry(segment2, segment2Abs.x - minX, segment2Abs.y - minY, segment2Abs.w, segment2Abs.h);
  maybeSetRectGeometry(segment3, segment3Abs.x - minX, segment3Abs.y - minY, segment3Abs.w, segment3Abs.h);

  arrow.vectorPaths = [{ windingRule: "NONZERO", data: arrowPath }];
  maybeSetVectorGeometry(arrow, arrowAbs.x - minX, arrowAbs.y - minY, arrowAbs.w, arrowAbs.h, 0);

  if (debugStart && debugMid && debugEnd) {
    maybeSetEllipseGeometry(debugStart, debugStartAbs.x - minX, debugStartAbs.y - minY, debugStartAbs.w, debugStartAbs.h);
    maybeSetEllipseGeometry(debugMid, debugMidAbs.x - minX, debugMidAbs.y - minY, debugMidAbs.w, debugMidAbs.h);
    maybeSetEllipseGeometry(debugEnd, debugEndAbs.x - minX, debugEndAbs.y - minY, debugEndAbs.w, debugEndAbs.h);
    debugStart.visible = debugEnabled;
    debugMid.visible = debugEnabled;
    debugEnd.visible = debugEnabled;
  }
}

function findFallbackChild<T extends SceneNode>(
  container: FrameNode,
  role: string,
  type: SceneNode["type"]
): T | null {
  const node = container.children.find((child) => child.type === type && child.getPluginData(FALLBACK_ROLE_KEY) === role);
  return (node as T | undefined) ?? null;
}

function getFallbackContainer(wrapper: GroupNode): FrameNode | null {
  const container = wrapper.children.find(
    (child): child is FrameNode => child.type === "FRAME" && child.getPluginData(FALLBACK_CONTAINER_ROLE) === "true"
  );
  return container ?? null;
}

async function syncFallbackLinks(): Promise<void> {
  if (isSyncingFallbackLinks) {
    return;
  }
  isSyncingFallbackLinks = true;
  try {
    const links = figma.currentPage.findAll(
      (node): node is GroupNode => node.type === "GROUP" && node.getPluginData(FALLBACK_LINK_MARK) === "true"
    );
    for (const wrapper of links) {
      const startNodeId = wrapper.getPluginData(FALLBACK_LINK_START_ID);
      const endNodeId = wrapper.getPluginData(FALLBACK_LINK_END_ID);
      if (!startNodeId || !endNodeId) {
        continue;
      }

      const [startNode, endNode] = await Promise.all([
        figma.getNodeByIdAsync(startNodeId),
        figma.getNodeByIdAsync(endNodeId)
      ]);
      if (!startNode || !endNode || !("x" in startNode) || !("x" in endNode)) {
        continue;
      }

      const startDim = startNode as SceneNode & DimensionAndPositionMixin;
      const endDim = endNode as SceneNode & DimensionAndPositionMixin;
      const startBounds = getNodeBoundsInPage(startDim);
      const endBounds = getNodeBoundsInPage(endDim);
      const direction: HorizontalMagnet =
        endBounds.x + endBounds.width / 2 >= startBounds.x + startBounds.width / 2 ? "RIGHT" : "LEFT";
      layoutFallbackShapeLink(wrapper, startDim, endDim, direction);
    }
  } finally {
    isSyncingFallbackLinks = false;
  }
}

function scheduleFallbackSync(): void {
  if (pendingSyncTimer) {
    return;
  }
  pendingSyncTimer = setTimeout(() => {
    pendingSyncTimer = null;
    void syncFallbackLinks();
  }, SYNC_THROTTLE_MS);
}

function ensureFallbackPolling(): void {
  if (fallbackPollingTimer) {
    return;
  }
  fallbackPollingTimer = setInterval(() => {
    void syncFallbackLinks();
  }, POLLING_SYNC_MS);
}

function applyDebugVisibilityToAllLinks(): void {
  const links = figma.currentPage.findAll(
    (node): node is GroupNode => node.type === "GROUP" && node.getPluginData(FALLBACK_LINK_MARK) === "true"
  );
  for (const wrapper of links) {
    const container = getFallbackContainer(wrapper);
    if (!container) {
      continue;
    }
    const debugStart = findFallbackChild<EllipseNode>(container, "debug-start", "ELLIPSE");
    const debugMid = findFallbackChild<EllipseNode>(container, "debug-mid", "ELLIPSE");
    const debugEnd = findFallbackChild<EllipseNode>(container, "debug-end", "ELLIPSE");
    if (debugStart) {
      debugStart.visible = debugEnabled;
    }
    if (debugMid) {
      debugMid.visible = debugEnabled;
    }
    if (debugEnd) {
      debugEnd.visible = debugEnabled;
    }
  }
}

function almostEqual(a: number, b: number): boolean {
  return Math.abs(a - b) <= GEOMETRY_EPSILON;
}

function maybeSetPosition(node: SceneNode & DimensionAndPositionMixin, x: number, y: number): void {
  if (!almostEqual(node.x, x)) {
    node.x = x;
  }
  if (!almostEqual(node.y, y)) {
    node.y = y;
  }
}

function maybeSetRectGeometry(node: RectangleNode, x: number, y: number, w: number, h: number): void {
  maybeSetPosition(node, x, y);
  if (!almostEqual(node.width, w) || !almostEqual(node.height, h)) {
    node.resize(w, h);
  }
}

function maybeSetEllipseGeometry(node: EllipseNode, x: number, y: number, w: number, h: number): void {
  maybeSetPosition(node, x, y);
  if (!almostEqual(node.width, w) || !almostEqual(node.height, h)) {
    node.resize(w, h);
  }
}

function maybeSetVectorGeometry(
  node: VectorNode,
  x: number,
  y: number,
  w: number,
  h: number,
  rotation: number
): void {
  maybeSetPosition(node, x, y);
  if (!almostEqual(node.width, w) || !almostEqual(node.height, h)) {
    node.resize(w, h);
  }
  if (!almostEqual(node.rotation, rotation)) {
    node.rotation = rotation;
  }
}

function hexToRgb(hex: string): RGB {
  const cleanHex = hex.replace("#", "");
  const parsed = parseInt(cleanHex, 16);
  return {
    r: ((parsed >> 16) & 255) / 255,
    g: ((parsed >> 8) & 255) / 255,
    b: (parsed & 255) / 255
  };
}

function sendStatus(kind: "success" | "error", message: string): void {
  figma.ui.postMessage({
    type: "status",
    payload: {
      kind,
      message
    }
  });
}
